---
# tasks file for dovecot

- name: Include Debian setup tasks
  include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install Dovecot packages
  ansible.builtin.package:
    name: "{{ dovecot_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure Dovecot (10-auth.conf)
  ansible.builtin.template:
    src: "10-auth.conf.j2"
    dest: "/etc/dovecot/conf.d/10-auth.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Dovecot

- name: Configure Dovecot (10-mail.conf)
  ansible.builtin.template:
    src: "10-mail.conf.j2"
    dest: "/etc/dovecot/conf.d/10-mail.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Dovecot

- name: Configure Dovecot (10-ssl.conf)
  ansible.builtin.template:
    src: "10-ssl.conf.j2"
    dest: "/etc/dovecot/conf.d/10-ssl.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Dovecot
