---
# handlers file for dovecot

- name: apt update
  ansible.builtin.apt:
    update_cache: true

- name: Restart Dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
    enabled: true
