---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_distribution == "Debian"

  roles:
    - role: lavery98.dovecot
