---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    dovecot_mysql_password: some_password

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Install postfix
      ansible.builtin.package:
        name: postfix
        state: present

  roles:
    - role: lavery98.dovecot
